let firstName;
let lastName;
let environment;
let website;
let campground;
let campsite;
let type;
let yearMin;
let monthMin;
let dayMin;
let yearMax;
let monthMax;
let dayMax;
let range;
let dateMin;
let dateMax;
let dateDiff;
let dates = [];
let dateFoundMap = {};
let found = false;
let sourceEmail;
let targetEmails = [];
let confirmedDates = [];
let currentDates = [];
let currentMonths = [];
let navigationComplete = false;
let login = false;
let headless = true;
let timeout = 0;

module.exports = { campground, campsite, confirmedDates, currentDates, currentMonths, dates, dateDiff, dateFoundMap, dateMin, dateMax, dayMax, dayMin, environment, firstName, found, headless, lastName, login, monthMax, monthMin, navigationComplete, range, sourceEmail, targetEmails, timeout, type, website, yearMax, yearMin };