let firstName;
let lastName;
let website;
let campground;
let campsite;
let type;
let yearMin;
let monthMin;
let dayMin;
let yearMax;
let monthMax;
let dayMax;
let range;
let dateMin;
let dateMax;
let dateDiff;
let dates = [];
let dateFoundMap = {};
let found = false;
let sourceEmail;
let targetEmails = [];
let confirmedDates = [];

module.exports = { campground, campsite, confirmedDates, dates, dateDiff, dateFoundMap, dateMin, dateMax, dayMax, dayMin, firstName, found, lastName, monthMax, monthMin, range, sourceEmail, targetEmails, type, website, yearMax, yearMin };