name: Deploy Node Modules

on: # On push to master, if node_modules, package.json, or package-lock.json has been changed
  push:
    branches:
      - master
    paths:
      - 'node_modules'
      - 'package.json'
      - 'package-lock.json'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        