name: Deploy Chromedriver

on:
  push:
    branches:
      - master
    paths:
      - 'chromedriver'  # If chromedriver has changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package Lambda Layer
        env: 
          release_bucket: camp-lite-dev
          release_bucket_uri: s3://camp-lite-dev/chromedriver
          release_id: ${{ format('chromedriver.zip', github.head_ref )}}
          release_layer: chromedriver
        run: |
          # Create a ZIP file containing chromedriver
          zip -qq $release_id chromedriver

          echo "release_id $release_id"
          echo "release_layer $release_layer"
          echo "release_bucket_uri $release_bucket_uri"

          # Copy the file to S3 and install it in Lambda Layer
          aws s3 cp $release_id $release_bucket_uri
          aws lambda publish-layer-version --layer-name $release_layer