name: Deploy Chromedriver

on:
  push:
    branches:
      - master
    paths:
      - 'chromedriver'  # If chromedriver has changed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          # Create a ZIP file containing chromedriver
          zip -qq chromedriver.zip chromedriver

          # Inspect contents
          unzip -l ./chromedriver.zip

          if [ -e "./chromedriver.zip" ]; then
            echo "File 'chromedriver.zip' exists."
          else
            echo "File 'chromedriver.zip' not found."
            exit 1
          fi

      - name: Debugging
        run: |
          ls -al
          pwd
          aws --version

      - name: Package Lambda Layer
        run: |
          # Copy the file to S3 and install it in Lambda Layer
          aws s3 cp ./chromedriver.zip s3://camp-lite-dev/chromedriver/chromedriver.zip
          # aws lambda publish-layer-version --layer-name chromedriver